### ISSUE TITLE
error raisedfrom sparsebit.quantization import QuantModel, parse_qconfig

### ISSUE THREAD

**Issue by wslgqq277g** [megvii-research/Sparsebit#17]

**Comment by wslgqq277g** [comment]
![image](https://user-images.githubusercontent.com/68363034/181904301-df1dc8ec-ea3f-4030-9827-9e3e32623699.png)
how to fix this problem

**Comment by wslgqq277g** [comment]
turned to docker the aforementioned problem has been solved........but where to find this .so file?
![2dcb82bede632ca6ae7bf9ef189ad1c](https://user-images.githubusercontent.com/68363034/181908952-0b563543-d207-468f-b1f8-dd2d890ac6fd.png)
![56560b39d78afd0eb5a283c6fa09ac8](https://user-images.githubusercontent.com/68363034/181908960-72db259f-6e26-49ae-a8e2-d575dcf1e040.png)

**Comment by PeiqinSun** [comment]
Please provide your installation details.

**Comment by Jiang-Stan** [comment]
The .so file should be automatically generated by running setup.py file for installation. Please check if you have successfully installed Sparsebit.
