### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by hsvlab** [megvii-research/Sparsebit#18]
Code jammed in “from sparsebit.quantization import QuantModel, parse_qconfig”, as shown in figure
<img width="554" alt="截屏2022-07-31 21 39 38" src="https://user-images.githubusercontent.com/97087248/182029224-addeed27-a6e4-482a-b46f-b2ec2fb7f077.png">

**Comment by PeiqinSun** [comment]
please provide your installation details.

**Comment by hsvlab** [comment]
> 

git clone https://github.com/megvii-research/Sparsebit.git
cd Sparsebit
pip install -v -e.

**Comment by Jiang-Stan** [comment]
> > 
> 
> git clone https://github.com/megvii-research/Sparsebit.git cd Sparsebit pip install -v -e.

Please try `python3 setup.py develop --user` for installation.

**Comment by hsvlab** [comment]
We reinstall the moudel use the command
 `python3 setup.py develop --user`
But raise another error`ModuleNotFoundError: No module named 'sparsebit.quantization'
<img width="698" alt="截屏2022-08-01 18 25 51" src="https://user-images.githubusercontent.com/97087248/182129257-e576b481-fd80-4b8a-87de-ed6a3d24cef0.png">

**Comment by Jiang-Stan** [comment]
Please check whether sparsebit is correctly installed(Or any error reported). Or the python env you used is not the python env you installed Sparsebit to.
