### ISSUE TITLE
Dimension mismatch when QAT model export to onnx 

### ISSUE THREAD

**Issue by SuperbTUM** [megvii-research/Sparsebit#22]
This issue can be easily reproduced with the [example of QAT](https://github.com/megvii-research/Sparsebit/blob/main/examples/cifar10_qat/main.ipynb), along with quant min, max disabled in PyTorch onnx operator. The error message comes from `quantizers/quant_tensor.py` saying `dimensions of scale and zero_point are inconsistent with input tensor`. I checked the scale and zero_point shape of first-layer convolution and it returns me with [3136, 1, 1, 1], where 3136=64\*7\*7, not [64, 1, 1, 1]...

**Comment by PeiqinSun** [comment]
The bug be fixed at https://github.com/megvii-research/Sparsebit/pull/20
