### ISSUE TITLE
error in homework Q3 code.

### ISSUE THREAD

**Issue by szhangNJU** [megvii-research/Sparsebit#30]
Homework ans, Q3 code
data.transpose(self.qdesc.ch_axis, 0)
here, 0 should be 1, the first axis (0) is the calibration-size, the second axis (1) is the channel axis according to the code.

and if self.qdesc.ch_axis==0 mean observers for weights, which should not be calculated here.

**Comment by Flying-Cloud** [comment]
1. First Question
    The code here is to switch the channel axis and batch-size axis.Here self.qdesc.ch_axis represents the channel axis , the first axis(0) represents the batch-size axis. 
2. Second Question
   It is true that weights should not use moving-average observer. Therefore, to avoid this issue, it is forbidden to add moving-average observer in qconfig.yaml.

**Comment by szhangNJU** [comment]
1.First Qusetion
   The moving average is calculated along axis 0. So, tansposing the channel axis to 0 is inappropriate.

**Comment by Flying-Cloud** [comment]
It is correct that "data.transpose" should be eliminated. Thank for your advice.
