### ISSUE TITLE
encounter keyerror when inputing module 

### ISSUE THREAD

**Issue by 42Shawn** [megvii-research/Sparsebit#58]
at this line,    
         elif n.op == "call_function":
                new_module = QMODULE_MAP[n.target](n)  # node作为module传入获取相关参数

KeyError: <built-in method conv2d of type object at 0x7fd352f76780>

**Comment by PeiqinSun** [comment]
1. Please provide more detailed model information. Like architecture?
2. Please print your n.target is what? n.target should be a string, not a nn.module

**Comment by 42Shawn** [comment]
谢谢回复！

我们直接打印这个n.target，输出的是<built-in method conv2d of type object at 0x7f7955bd7780>
打印了这个n.target的type，输出了<class 'builtin_function_or_method'>

**Comment by PeiqinSun** [comment]
太久没有回复故关闭issue
